workflows:
  default-workflow:
    name: IthalatHub Live Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.2
    triggering:
      events:
        - push
    scripts:
      - name: Recreate Android Project
        script: |
          rm -rf android
          flutter create --platforms=android --org com.ithalathub .
      - name: Inject Internet Permission
        script: |
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET"/>
              <application
                  android:label="İthalatHub"
                  android:name="\${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <meta-data
                        android:name="io.flutter.embedding.android.NormalTheme"
                        android:resource="@style/NormalTheme"
                        />
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>
          EOF
      - name: Clean and Get Packages
        script: |
          flutter pub clean
          flutter pub get
      - name: Generate App Launcher Icons
        script: |
          # Simge değiştirme paketini kurup logoyu telefon ikonuna basıyoruz
          flutter pub add flutter_launcher_icons --dev
          cat <<EOF > flutter_launcher_icons.yaml
          flutter_launcher_icons:
            android: "launcher_icon"
            image_path: "logo.png"
          EOF
          flutter pub run flutter_launcher_icons:main
      - name: Build Android APK (Release)
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
