workflows:
  default-workflow:
    name: IthalatHub Live Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Recreate Android Project (Fix V1 Embedding)
        script: |
          # Eski sıkıntılı android klasörünü sunucuda tamamen siliyoruz
          rm -rf android
          # Flutter'a sıfır kilometre, en güncel standartta Android altyapısı kurduruyoruz
          flutter create --platforms=android .
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK (Release)
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
